# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: minirag/v1/storage.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'minirag/v1/storage.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18minirag/v1/storage.proto\x12\nminirag.v1\"\xbf\x01\n\x06Record\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n\x06vector\x18\x02 \x03(\x02R\x06vector\x12\x12\n\x04text\x18\x03 \x01(\tR\x04text\x12<\n\x08metadata\x18\x04 \x03(\x0b\x32 .minirag.v1.Record.MetadataEntryR\x08metadata\x1a;\n\rMetadataEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n\x05value\x18\x02 \x01(\tR\x05value:\x02\x38\x01\";\n\rInsertRequest\x12*\n\x06record\x18\x01 \x01(\x0b\x32\x12.minirag.v1.RecordR\x06record\"\x10\n\x0eInsertResponse\"\x1c\n\nGetRequest\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\"9\n\x0bGetResponse\x12*\n\x06record\x18\x01 \x01(\x0b\x32\x12.minirag.v1.RecordR\x06record\"\x1f\n\rDeleteRequest\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\"\x10\n\x0e\x44\x65leteResponse\"3\n\rSearchRequest\x12\x14\n\x05query\x18\x01 \x03(\x02R\x05query\x12\x0c\n\x01k\x18\x02 \x01(\x05R\x01k\"4\n\x0cSearchResult\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n\x05score\x18\x02 \x01(\x02R\x05score\"D\n\x0eSearchResponse\x12\x32\n\x07results\x18\x01 \x03(\x0b\x32\x18.minirag.v1.SearchResultR\x07results2\x8f\x02\n\x12VectorStoreService\x12?\n\x06Insert\x12\x19.minirag.v1.InsertRequest\x1a\x1a.minirag.v1.InsertResponse\x12\x36\n\x03Get\x12\x16.minirag.v1.GetRequest\x1a\x17.minirag.v1.GetResponse\x12?\n\x06\x44\x65lete\x12\x19.minirag.v1.DeleteRequest\x1a\x1a.minirag.v1.DeleteResponse\x12?\n\x06Search\x12\x19.minirag.v1.SearchRequest\x1a\x1a.minirag.v1.SearchResponseB7Z5github.com/pfyao1101/miniRAG/api/minirag/v1;miniragv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'minirag.v1.storage_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z5github.com/pfyao1101/miniRAG/api/minirag/v1;miniragv1'
  _globals['_RECORD_METADATAENTRY']._loaded_options = None
  _globals['_RECORD_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_RECORD']._serialized_start=41
  _globals['_RECORD']._serialized_end=232
  _globals['_RECORD_METADATAENTRY']._serialized_start=173
  _globals['_RECORD_METADATAENTRY']._serialized_end=232
  _globals['_INSERTREQUEST']._serialized_start=234
  _globals['_INSERTREQUEST']._serialized_end=293
  _globals['_INSERTRESPONSE']._serialized_start=295
  _globals['_INSERTRESPONSE']._serialized_end=311
  _globals['_GETREQUEST']._serialized_start=313
  _globals['_GETREQUEST']._serialized_end=341
  _globals['_GETRESPONSE']._serialized_start=343
  _globals['_GETRESPONSE']._serialized_end=400
  _globals['_DELETEREQUEST']._serialized_start=402
  _globals['_DELETEREQUEST']._serialized_end=433
  _globals['_DELETERESPONSE']._serialized_start=435
  _globals['_DELETERESPONSE']._serialized_end=451
  _globals['_SEARCHREQUEST']._serialized_start=453
  _globals['_SEARCHREQUEST']._serialized_end=504
  _globals['_SEARCHRESULT']._serialized_start=506
  _globals['_SEARCHRESULT']._serialized_end=558
  _globals['_SEARCHRESPONSE']._serialized_start=560
  _globals['_SEARCHRESPONSE']._serialized_end=628
  _globals['_VECTORSTORESERVICE']._serialized_start=631
  _globals['_VECTORSTORESERVICE']._serialized_end=902
# @@protoc_insertion_point(module_scope)
