# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from minirag.v1 import storage_pb2 as minirag_dot_v1_dot_storage__pb2


class VectorStoreServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Insert = channel.unary_unary(
                '/minirag.v1.VectorStoreService/Insert',
                request_serializer=minirag_dot_v1_dot_storage__pb2.InsertRequest.SerializeToString,
                response_deserializer=minirag_dot_v1_dot_storage__pb2.InsertResponse.FromString,
                _registered_method=True)
        self.Get = channel.unary_unary(
                '/minirag.v1.VectorStoreService/Get',
                request_serializer=minirag_dot_v1_dot_storage__pb2.GetRequest.SerializeToString,
                response_deserializer=minirag_dot_v1_dot_storage__pb2.GetResponse.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/minirag.v1.VectorStoreService/Delete',
                request_serializer=minirag_dot_v1_dot_storage__pb2.DeleteRequest.SerializeToString,
                response_deserializer=minirag_dot_v1_dot_storage__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.Search = channel.unary_unary(
                '/minirag.v1.VectorStoreService/Search',
                request_serializer=minirag_dot_v1_dot_storage__pb2.SearchRequest.SerializeToString,
                response_deserializer=minirag_dot_v1_dot_storage__pb2.SearchResponse.FromString,
                _registered_method=True)


class VectorStoreServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Insert(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Search(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VectorStoreServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Insert': grpc.unary_unary_rpc_method_handler(
                    servicer.Insert,
                    request_deserializer=minirag_dot_v1_dot_storage__pb2.InsertRequest.FromString,
                    response_serializer=minirag_dot_v1_dot_storage__pb2.InsertResponse.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=minirag_dot_v1_dot_storage__pb2.GetRequest.FromString,
                    response_serializer=minirag_dot_v1_dot_storage__pb2.GetResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=minirag_dot_v1_dot_storage__pb2.DeleteRequest.FromString,
                    response_serializer=minirag_dot_v1_dot_storage__pb2.DeleteResponse.SerializeToString,
            ),
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=minirag_dot_v1_dot_storage__pb2.SearchRequest.FromString,
                    response_serializer=minirag_dot_v1_dot_storage__pb2.SearchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'minirag.v1.VectorStoreService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('minirag.v1.VectorStoreService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VectorStoreService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Insert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/minirag.v1.VectorStoreService/Insert',
            minirag_dot_v1_dot_storage__pb2.InsertRequest.SerializeToString,
            minirag_dot_v1_dot_storage__pb2.InsertResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/minirag.v1.VectorStoreService/Get',
            minirag_dot_v1_dot_storage__pb2.GetRequest.SerializeToString,
            minirag_dot_v1_dot_storage__pb2.GetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/minirag.v1.VectorStoreService/Delete',
            minirag_dot_v1_dot_storage__pb2.DeleteRequest.SerializeToString,
            minirag_dot_v1_dot_storage__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/minirag.v1.VectorStoreService/Search',
            minirag_dot_v1_dot_storage__pb2.SearchRequest.SerializeToString,
            minirag_dot_v1_dot_storage__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
